# Generated by Django 3.2.6 on 2022-08-26 17:04

import apps.home.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('address2', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('state', models.CharField(blank=True, default='', max_length=30)),
                ('zip', models.CharField(blank=True, default='', max_length=5)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('ice1_fname', models.CharField(blank=True, default='', max_length=30)),
                ('ice1_lname', models.CharField(blank=True, default='', max_length=30)),
                ('ice1_phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('ice1_relationship', models.CharField(blank=True, default='', max_length=30)),
                ('ice2_fname', models.CharField(blank=True, default='', max_length=30)),
                ('ice2_lname', models.CharField(blank=True, default='', max_length=30)),
                ('ice2_phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('ice2_relationship', models.CharField(blank=True, default='', max_length=30)),
                ('exit_reason', models.CharField(blank=True, default='', max_length=30)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=30)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('image', models.ImageField(blank=True, default='', upload_to='employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liquidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.CharField(blank=True, default='', max_length=30)),
                ('contact_phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('contact_email', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, default='', max_length=30)),
                ('category', models.CharField(choices=[('APPAREL', 'APPAREL'), ('APPLIANCES - LARGE', 'APPLIANCES - LARGE'), ('APPLIANCES - SMALL', 'APPLIANCES - SMALL'), ('BIKES & RIDE ONS', 'BIKES & RIDE ONS'), ('CONSUMER ELECTRONICS', 'CONSUMER ELECTRONICS'), ('COOKWARE', 'COOKWARE'), ('DOMESTICS', 'DOMESTICS'), ('FOOD', 'FOOD'), ('FOOTWEAR', 'FOOTWEAR'), ('FURNITURE', 'FURNITURE'), ('GARDEN / PATIO', 'GARDEN / PATIO'), ('GENERAL MERCHANDISE', 'GENERAL MERCHANDISE'), ('HARDWARE', 'HARDWARE'), ('HEALTH & BEAUTY', 'HEALTH & BEAUTY'), ('HOME DECOR', 'HOME DECOR'), ('JEWELRY', 'JEWELRY'), ('LUGGAGE', 'LUGGAGE'), ('MAJOR APPLIANCES', 'MAJOR APPLIANCES'), ('MIXED LOTS', 'MIXED LOTS'), ('RUGS', 'RUGS'), ('SEASONAL', 'SEASONAL'), ('SPORTING GOODS', 'SPORTING GOODS'), ('TOOLS', 'TOOLS'), ('TOYS', 'TOYS'), ('TVS', 'TVS'), ('VACUUMS', 'VACUUMS')], max_length=30)),
                ('item_count', models.IntegerField(default=0)),
                ('pallet_count', models.IntegerField(default=0)),
                ('sale_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('purchase_date', models.DateField(blank=True, default=None, null=True)),
                ('delivery_date', models.DateField(blank=True, default=None, null=True)),
                ('pod_image', models.ImageField(default=None, null=True, upload_to=apps.home.models.PathAndRename('orders'))),
                ('manifest_file', models.FileField(default=None, null=True, upload_to=apps.home.models.PathAndRename('orders'))),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_orders', to='home.employee')),
                ('liquidator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.liquidator')),
                ('unloaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unloaded_orders', to='home.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('address2', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('state', models.CharField(blank=True, default='', max_length=30)),
                ('zip', models.CharField(blank=True, default='', max_length=5)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('general_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stores', to='home.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to=apps.home.models.PathAndRename('orders'))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='Consignor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
