# Generated by Django 3.2.6 on 2022-09-23 16:23

import apps.home.variables
import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dropoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('comments', models.CharField(blank=True, default='', max_length=100)),
                ('agreement_image', models.ImageField(blank=True, default='', upload_to=apps.home.variables.PathAndRename('dropoff-agreement'))),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dropoff_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, default=datetime.date.today)),
                ('zero_date', models.DateField(blank=True, default=None, null=True)),
                ('change_date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('condition', models.CharField(blank=True, choices=[('New - Brand New', 'BrandNew'), ('New - Excellent', 'NewExcellent'), ('New - Very Good', 'NewVeryGood'), ('New - Good', 'NewGood'), ('New - Acceptable', 'NewAcceptable'), ('New - Poor', 'NewPoor'), ('New - Salvage', 'NewSalvage'), ('Used - Excellent', 'UsedExcellent'), ('Used - Very Good', 'UsedVeryGood'), ('Used - Good', 'UsedGood'), ('Used - Acceptable', 'UsedAcceptable'), ('Used - Poor', 'UsedPoor'), ('Used - Salvage', 'UsedSalvage'), ('Reject - Condition', 'Condition'), ('Reject - Dirty', 'Dirty'), ('Reject - MissingParts', 'MissingParts'), ('Reject - Violation', 'Violation')], default='', max_length=50)),
                ('tested', models.CharField(blank=True, choices=[('Not Tested', 'NotTested'), ('Tested - Works Perfect', 'WorksPerfect'), ('Tested - Works Okay', 'WorksOk'), ('Tested - Works Some Damage', 'SomeDamage'), ('Tested - Works Heavy Damage', 'HeavyDamage'), ('Tested - Repairable Light', 'RepairableLight'), ('Tested - Repairable Heavy', 'RepairableHeavy'), ('Tested - Salvage', 'Salvage')], default='', max_length=50)),
                ('tags', models.CharField(blank=True, default='', max_length=999)),
                ('price_code', models.CharField(blank=True, default='', max_length=2)),
                ('static_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('status_change', models.CharField(blank=True, choices=[('Lost', 'Lost'), ('Stolen', 'Stolen'), ('Broken - Kept', 'BrokenKept'), ('Broken - Recycled', 'BrokenRecycled'), ('Broken - Disposed', 'BrokenDisposed'), ('Broken - Free', 'BrokenFree'), ('Removed - Donation', 'RemovedDonation'), ('Removed - Violation', 'RemovedViolation'), ('Removed - Returned', 'RemovedReturned'), ('Removed - Moved', 'RemovedMoved')], default='', max_length=50)),
                ('dropoff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.dropoff')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.CharField(blank=True, default='', max_length=100)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US')),
                ('contact_email', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, default='', max_length=30)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('item_count', models.IntegerField(blank=True, default=0)),
                ('pallet_count', models.IntegerField(blank=True, default=0)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('shipping_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('purchase_date', models.DateField(blank=True, default=datetime.date.today)),
                ('delivery_date', models.DateField(blank=True, default=None, null=True)),
                ('pod_image', models.ImageField(blank=True, default='', upload_to=apps.home.variables.PathAndRename('order-pod'))),
                ('manifest_file', models.FileField(blank=True, default=None, null=True, upload_to=apps.home.variables.PathAndRename('order-manifest'))),
                ('liquidator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.liquidator')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('address2', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('state', models.CharField(blank=True, choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], default='', max_length=2)),
                ('zip', models.CharField(blank=True, default='', max_length=5)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US')),
                ('email', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consignor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.extendeduser')),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('address2', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('state', models.CharField(blank=True, choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], default='', max_length=2)),
                ('zip', models.CharField(blank=True, default='', max_length=5)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US')),
                ('waiver_image', models.ImageField(blank=True, default='', upload_to=apps.home.variables.PathAndRename('user-consignor-waiver'))),
                ('waiver_date', models.DateField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, default='', upload_to=apps.home.variables.PathAndRename('user-consignor-image'))),
                ('pid_type', models.CharField(blank=True, choices=[('Drivers Liscense', 'DriversLiscense'), ('Passport', 'Passport'), ('Student ID', 'StudentID')], default='', max_length=50)),
                ('pid_image', models.ImageField(blank=True, default='', upload_to=apps.home.variables.PathAndRename('user-consignor-pid'))),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.extendeduser')),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('address2', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('state', models.CharField(blank=True, choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], default='', max_length=2)),
                ('zip', models.CharField(blank=True, default='', max_length=5)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US')),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('ice1_fname', models.CharField(blank=True, default='', max_length=30)),
                ('ice1_lname', models.CharField(blank=True, default='', max_length=30)),
                ('ice1_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US')),
                ('ice1_relationship', models.CharField(blank=True, default='', max_length=30)),
                ('ice2_fname', models.CharField(blank=True, default='', max_length=30)),
                ('ice2_lname', models.CharField(blank=True, default='', max_length=30)),
                ('ice2_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US')),
                ('ice2_relationship', models.CharField(blank=True, default='', max_length=30)),
                ('exit_reason', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateField(blank=True, default=datetime.date(1, 1, 1))),
                ('end_date', models.DateField(blank=True, default=datetime.date(9999, 12, 31))),
                ('title', models.CharField(blank=True, default='', max_length=30)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, default='', upload_to=apps.home.variables.PathAndRename('user-employee-image'))),
            ],
        ),
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.extendeduser')),
                ('waiver_image', models.ImageField(blank=True, default='', upload_to=apps.home.variables.PathAndRename('user-shopper-waiver'))),
                ('waiver_date', models.DateField(blank=True, default=None, null=True)),
                ('email_preferences', models.CharField(blank=True, choices=[('All Emails', 'All Emails'), ('No Emails', 'No Emails')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.store')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to=apps.home.variables.PathAndRename('order-image'))),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=5)),
                ('section', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.section')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to=apps.home.variables.PathAndRename('item-image'))),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.order'),
        ),
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.section'),
        ),
        migrations.AddField(
            model_name='department',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='general_manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='accepted_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_orders', to='home.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='unloaded_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unloaded_orders', to='home.employee'),
        ),
        migrations.AddField(
            model_name='item',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee'),
        ),
        migrations.AddField(
            model_name='dropoff',
            name='consignor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.consignor'),
        ),
        migrations.AddField(
            model_name='dropoff',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee'),
        ),
    ]
