# Generated by Django 3.2.6 on 2022-08-26 18:20

import apps.home.models
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignor',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consignor',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consignor',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='consignor',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=apps.home.models.PathAndRename('user-consignor-image')),
        ),
        migrations.AddField(
            model_name='consignor',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AddField(
            model_name='consignor',
            name='pid_image',
            field=models.ImageField(blank=True, default='', upload_to=apps.home.models.PathAndRename('user-consignor-pid')),
        ),
        migrations.AddField(
            model_name='consignor',
            name='pid_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='consignor',
            name='state',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='consignor',
            name='waiver_image',
            field=models.ImageField(blank=True, default='', upload_to=apps.home.models.PathAndRename('user-consignor-waiver')),
        ),
        migrations.AddField(
            model_name='consignor',
            name='zip',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='shopper',
            name='email_promotions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopper',
            name='waiver_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='shopper',
            name='waiver_image',
            field=models.ImageField(blank=True, default='', upload_to=apps.home.models.PathAndRename('user-shopper-waiver')),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=apps.home.models.PathAndRename('user-employee-image')),
        ),
        migrations.AlterField(
            model_name='order',
            name='manifest_file',
            field=models.FileField(default=None, null=True, upload_to=apps.home.models.PathAndRename('order-manifest')),
        ),
        migrations.AlterField(
            model_name='order',
            name='pod_image',
            field=models.ImageField(default=None, null=True, upload_to=apps.home.models.PathAndRename('order-pod')),
        ),
        migrations.AlterField(
            model_name='orderimages',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=apps.home.models.PathAndRename('order-image')),
        ),
    ]
