# Generated by Django 3.2.6 on 2022-09-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dropoff_Line',
        ),
        migrations.RemoveField(
            model_name='item_images',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order_images',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order_Line',
        ),
        migrations.DeleteModel(
            name='Item_Images',
        ),
        migrations.DeleteModel(
            name='Order_Images',
        ),
    ]
