# Generated by Django 3.2.6 on 2022-10-05 18:06

import apps.home.variables
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220929_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='change_date',
            new_name='status_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='section',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status_change',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=apps.home.variables.PathAndRename('item-image')),
        ),
        migrations.AddField(
            model_name='item',
            name='item_class',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('Lost', 'Lost'), ('Stolen', 'Stolen'), ('Broken - Kept', 'BrokenKept'), ('Broken - Recycled', 'BrokenRecycled'), ('Broken - Disposed', 'BrokenDisposed'), ('Broken - Free', 'BrokenFree'), ('Removed - Donation', 'RemovedDonation'), ('Removed - Violation', 'RemovedViolation'), ('Removed - Returned', 'RemovedReturned'), ('Removed - Moved', 'RemovedMoved'), ('Undelivered', 'Undelivered')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_retail',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='units',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
