# Generated by Django 3.2.6 on 2022-10-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221005_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignor',
            name='pid_type',
            field=models.CharField(blank=True, choices=[('DriversLiscense', 'Drivers Liscense'), ('Passport', 'Passport'), ('StudentID', 'Student ID')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, choices=[('BrandNew', 'New - Brand New'), ('NewExcellent', 'New - Excellent'), ('NewVeryGood', 'New - Very Good'), ('NewGood', 'New - Good'), ('NewAcceptable', 'New - Acceptable'), ('NewPoor', 'New - Poor'), ('NewSalvage', 'New - Salvage'), ('UsedExcellent', 'Used - Excellent'), ('UsedVeryGood', 'Used - Very Good'), ('UsedGood', 'Used - Good'), ('UsedAcceptable', 'Used - Acceptable'), ('UsedPoor', 'Used - Poor'), ('UsedSalvage', 'Used - Salvage'), ('Condition', 'Reject - Condition'), ('Dirty', 'Reject - Dirty'), ('MissingParts', 'Reject - MissingParts'), ('Violation', 'Reject - Violation')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('CheckedIn', 'Checked-In'), ('Delivered', 'Delivered'), ('Undelivered', 'Undelivered'), ('Unfulfilled', 'Unfulfilled'), ('Lost', 'Lost'), ('Stolen', 'Stolen'), ('BrokenKept', 'Broken - Kept'), ('BrokenRecycled', 'Broken - Recycled'), ('BrokenDisposed', 'Broken - Disposed'), ('BrokenFree', 'Broken - Free'), ('RemovedDonation', 'Removed - Donation'), ('RemovedViolation', 'Removed - Violation'), ('RemovedReturned', 'Removed - Returned'), ('RemovedMoved', 'Removed - Moved')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='tested',
            field=models.CharField(blank=True, choices=[('NotTested', 'Not Tested'), ('WorksPerfect', 'Tested - Works Perfect'), ('WorksOk', 'Tested - Works Okay'), ('SomeDamage', 'Tested - Works Some Damage'), ('HeavyDamage', 'Tested - Works Heavy Damage'), ('RepairableLight', 'Tested - Repairable Light'), ('RepairableHeavy', 'Tested - Repairable Heavy'), ('Salvage', 'Tested - Salvage')], default='', max_length=50),
        ),
    ]
