# Generated by Django 3.2.6 on 2022-08-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220829_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper',
            name='email_promotions',
        ),
        migrations.AddField(
            model_name='shopper',
            name='email_preferences',
            field=models.CharField(blank=True, choices=[('All Emails', 'All Emails'), ('No Emails', 'No Emails')], default='', max_length=30),
        ),
    ]
