# Generated by Django 3.2.6 on 2022-08-30 19:06

import apps.home.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220830_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=1000)),
                ('agreement_image', models.ImageField(default=None, null=True, upload_to=apps.home.models.PathAndRename('dropoff-agreement'))),
                ('offer_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('consignor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.consignor')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee')),
            ],
        ),
    ]
