# Generated by Django 3.2.6 on 2022-10-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221017_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='unit_retail',
            new_name='retail_amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='units',
        ),
    ]
