# Generated by Django 3.2.6 on 2022-08-30 19:40

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_dropoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropoff',
            name='agreement_image',
            field=models.ImageField(blank=True, default='', upload_to=apps.home.models.PathAndRename('dropoff-agreement')),
        ),
        migrations.AlterField(
            model_name='order',
            name='manifest_file',
            field=models.FileField(blank=True, default='', upload_to=apps.home.models.PathAndRename('order-manifest')),
        ),
        migrations.AlterField(
            model_name='order',
            name='pod_image',
            field=models.ImageField(blank=True, default='', upload_to=apps.home.models.PathAndRename('order-pod')),
        ),
        migrations.AlterField(
            model_name='orderimages',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=apps.home.models.PathAndRename('order-image')),
        ),
    ]
