# Generated by Django 3.2.6 on 2022-08-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Checkout', 'Checkout'), ('Expensive Items', 'ExpensiveItems'), ('General Items', 'GeneralItems'), ('Inventory', 'Inventory'), ('Kids Apparel', 'KidsApparel'), ('Large Items', 'LargeItems'), ('Processing', 'Processing')], max_length=30),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.department')),
            ],
        ),
    ]
